// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Srotas.Data;

#nullable disable

namespace Srotas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220525184805_nullablerating")]
    partial class nullablerating
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Srotas.Models.AutomobilioSkelbimas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Gamintojas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Kaina")
                        .HasColumnType("float");

                    b.Property<int>("KoloneliuSkersmuo")
                        .HasColumnType("int");

                    b.Property<string>("KuroTipas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PagaminimoMetai")
                        .HasColumnType("int");

                    b.Property<int>("PardavejasId")
                        .HasColumnType("int");

                    b.Property<bool>("Parduotas")
                        .HasColumnType("bit");

                    b.Property<string>("PavaruDezesTipas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RatuDydis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RatuPlotis")
                        .HasColumnType("int");

                    b.Property<int>("Rida")
                        .HasColumnType("int");

                    b.Property<string>("Spalva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TuriDuris")
                        .HasColumnType("bit");

                    b.Property<bool>("TuriKapota")
                        .HasColumnType("bit");

                    b.Property<bool>("TuriKoloneles")
                        .HasColumnType("bit");

                    b.Property<bool>("TuriPavaruDeze")
                        .HasColumnType("bit");

                    b.Property<bool>("TuriRatus")
                        .HasColumnType("bit");

                    b.Property<bool>("TuriVarikli")
                        .HasColumnType("bit");

                    b.Property<int?>("UzsakymasId")
                        .HasColumnType("int");

                    b.Property<double>("VariklioTuris")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PardavejasId");

                    b.HasIndex("UzsakymasId");

                    b.ToTable("AutomobilioSkelbimas");
                });

            modelBuilder.Entity("Srotas.Models.Durys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Gamintojas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Kaina")
                        .HasColumnType("float");

                    b.Property<string>("Modelis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PagaminimoMetai")
                        .HasColumnType("int");

                    b.Property<int>("PardavejasId")
                        .HasColumnType("int");

                    b.Property<bool>("Parduotas")
                        .HasColumnType("bit");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spalva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UzsakymasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PardavejasId");

                    b.HasIndex("UzsakymasId");

                    b.ToTable("Durys");
                });

            modelBuilder.Entity("Srotas.Models.Kapotas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Gamintojas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Kaina")
                        .HasColumnType("float");

                    b.Property<string>("Modelis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PagaminimoMetai")
                        .HasColumnType("int");

                    b.Property<int>("PardavejasId")
                        .HasColumnType("int");

                    b.Property<bool>("Parduotas")
                        .HasColumnType("bit");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spalva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UzsakymasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PardavejasId");

                    b.HasIndex("UzsakymasId");

                    b.ToTable("Kapotas");
                });

            modelBuilder.Entity("Srotas.Models.Koloneles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Gamintojas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Kaina")
                        .HasColumnType("float");

                    b.Property<int>("PardavejasId")
                        .HasColumnType("int");

                    b.Property<bool>("Parduotas")
                        .HasColumnType("bit");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Skersmuo")
                        .HasColumnType("int");

                    b.Property<int?>("UzsakymasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PardavejasId");

                    b.HasIndex("UzsakymasId");

                    b.ToTable("Koloneles");
                });

            modelBuilder.Entity("Srotas.Models.Nuolaida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ArPanaudota")
                        .HasColumnType("bit");

                    b.Property<string>("Kodas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PardavejasId")
                        .HasColumnType("int");

                    b.Property<double>("Procentai")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PardavejasId");

                    b.ToTable("Nuolaida");
                });

            modelBuilder.Entity("Srotas.Models.Pardavejas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Reitingas")
                        .HasColumnType("float");

                    b.Property<string>("Saptazodis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slapyvardis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("elPastas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pardavejas");
                });

            modelBuilder.Entity("Srotas.Models.PavaruDeze", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Gamintojas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Kaina")
                        .HasColumnType("float");

                    b.Property<int>("PardavejasId")
                        .HasColumnType("int");

                    b.Property<bool>("Parduotas")
                        .HasColumnType("bit");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UzsakymasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PardavejasId");

                    b.HasIndex("UzsakymasId");

                    b.ToTable("PavaruDeze");
                });

            modelBuilder.Entity("Srotas.Models.Pirkejas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Balansas")
                        .HasColumnType("float");

                    b.Property<string>("Saptazodis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slapyvardis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("elPastas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pirkejas");
                });

            modelBuilder.Entity("Srotas.Models.Ratai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Dydis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gamintojas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Kaina")
                        .HasColumnType("float");

                    b.Property<int>("PardavejasId")
                        .HasColumnType("int");

                    b.Property<bool>("Parduotas")
                        .HasColumnType("bit");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plotis")
                        .HasColumnType("int");

                    b.Property<int?>("UzsakymasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PardavejasId");

                    b.HasIndex("UzsakymasId");

                    b.ToTable("Ratai");
                });

            modelBuilder.Entity("Srotas.Models.Uzsakymas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Ivertinimas")
                        .HasColumnType("int");

                    b.Property<string>("Kodas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PirkejasId")
                        .HasColumnType("int");

                    b.Property<double>("Suma")
                        .HasColumnType("float");

                    b.Property<DateTime>("pristatymoData")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PirkejasId");

                    b.ToTable("Uzsakymas");
                });

            modelBuilder.Entity("Srotas.Models.Variklis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Gamintojas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Kaina")
                        .HasColumnType("float");

                    b.Property<string>("KuroTipas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PardavejasId")
                        .HasColumnType("int");

                    b.Property<bool>("Parduotas")
                        .HasColumnType("bit");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Turis")
                        .HasColumnType("float");

                    b.Property<int?>("UzsakymasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PardavejasId");

                    b.HasIndex("UzsakymasId");

                    b.ToTable("Variklis");
                });

            modelBuilder.Entity("Srotas.Models.AutomobilioSkelbimas", b =>
                {
                    b.HasOne("Srotas.Models.Pardavejas", "Pardavejas")
                        .WithMany("Automobiliai")
                        .HasForeignKey("PardavejasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Srotas.Models.Uzsakymas", "Uzsakymas")
                        .WithMany("Automobiliai")
                        .HasForeignKey("UzsakymasId");

                    b.Navigation("Pardavejas");

                    b.Navigation("Uzsakymas");
                });

            modelBuilder.Entity("Srotas.Models.Durys", b =>
                {
                    b.HasOne("Srotas.Models.Pardavejas", "Pardavejas")
                        .WithMany("Durys")
                        .HasForeignKey("PardavejasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Srotas.Models.Uzsakymas", "Uzsakymas")
                        .WithMany("Durys")
                        .HasForeignKey("UzsakymasId");

                    b.Navigation("Pardavejas");

                    b.Navigation("Uzsakymas");
                });

            modelBuilder.Entity("Srotas.Models.Kapotas", b =>
                {
                    b.HasOne("Srotas.Models.Pardavejas", "Pardavejas")
                        .WithMany("Kapotai")
                        .HasForeignKey("PardavejasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Srotas.Models.Uzsakymas", "Uzsakymas")
                        .WithMany("Kapotai")
                        .HasForeignKey("UzsakymasId");

                    b.Navigation("Pardavejas");

                    b.Navigation("Uzsakymas");
                });

            modelBuilder.Entity("Srotas.Models.Koloneles", b =>
                {
                    b.HasOne("Srotas.Models.Pardavejas", "Pardavejas")
                        .WithMany("Koloneles")
                        .HasForeignKey("PardavejasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Srotas.Models.Uzsakymas", "Uzsakymas")
                        .WithMany("Koloneles")
                        .HasForeignKey("UzsakymasId");

                    b.Navigation("Pardavejas");

                    b.Navigation("Uzsakymas");
                });

            modelBuilder.Entity("Srotas.Models.Nuolaida", b =>
                {
                    b.HasOne("Srotas.Models.Pardavejas", "Pardavejas")
                        .WithMany("Nuolaidos")
                        .HasForeignKey("PardavejasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pardavejas");
                });

            modelBuilder.Entity("Srotas.Models.PavaruDeze", b =>
                {
                    b.HasOne("Srotas.Models.Pardavejas", "Pardavejas")
                        .WithMany("PavaruDezes")
                        .HasForeignKey("PardavejasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Srotas.Models.Uzsakymas", "Uzsakymas")
                        .WithMany("PavaruDezes")
                        .HasForeignKey("UzsakymasId");

                    b.Navigation("Pardavejas");

                    b.Navigation("Uzsakymas");
                });

            modelBuilder.Entity("Srotas.Models.Ratai", b =>
                {
                    b.HasOne("Srotas.Models.Pardavejas", "Pardavejas")
                        .WithMany("Ratai")
                        .HasForeignKey("PardavejasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Srotas.Models.Uzsakymas", "Uzsakymas")
                        .WithMany("Ratai")
                        .HasForeignKey("UzsakymasId");

                    b.Navigation("Pardavejas");

                    b.Navigation("Uzsakymas");
                });

            modelBuilder.Entity("Srotas.Models.Uzsakymas", b =>
                {
                    b.HasOne("Srotas.Models.Pirkejas", "Pirkejas")
                        .WithMany("Uzsakymai")
                        .HasForeignKey("PirkejasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pirkejas");
                });

            modelBuilder.Entity("Srotas.Models.Variklis", b =>
                {
                    b.HasOne("Srotas.Models.Pardavejas", "Pardavejas")
                        .WithMany("Varikiai")
                        .HasForeignKey("PardavejasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Srotas.Models.Uzsakymas", "Uzsakymas")
                        .WithMany("Varikiai")
                        .HasForeignKey("UzsakymasId");

                    b.Navigation("Pardavejas");

                    b.Navigation("Uzsakymas");
                });

            modelBuilder.Entity("Srotas.Models.Pardavejas", b =>
                {
                    b.Navigation("Automobiliai");

                    b.Navigation("Durys");

                    b.Navigation("Kapotai");

                    b.Navigation("Koloneles");

                    b.Navigation("Nuolaidos");

                    b.Navigation("PavaruDezes");

                    b.Navigation("Ratai");

                    b.Navigation("Varikiai");
                });

            modelBuilder.Entity("Srotas.Models.Pirkejas", b =>
                {
                    b.Navigation("Uzsakymai");
                });

            modelBuilder.Entity("Srotas.Models.Uzsakymas", b =>
                {
                    b.Navigation("Automobiliai");

                    b.Navigation("Durys");

                    b.Navigation("Kapotai");

                    b.Navigation("Koloneles");

                    b.Navigation("PavaruDezes");

                    b.Navigation("Ratai");

                    b.Navigation("Varikiai");
                });
#pragma warning restore 612, 618
        }
    }
}
